#!/bin/sh

$HOME/.config/bspwm/autostart.sh

#BSPWM configuration
#bspc config border_radius       8
bspc config border_width         2
bspc config window_gap           10
bspc config top_padding          30
bspc config bottom_padding       10
bspc config left_padding         10
bspc config right_padding        10
bspc config single_monocle       false
#bspc config click_to_focus       true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config focus_by_distance    true
bspc config focus_follows_pointer true
#bspc config history_aware_focus  true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

bspc config normal_border_color		"#4c566a"
bspc config active_border_color		"#1e1e1e"
bspc config focused_border_color	"#1f222f"
bspc config presel_feedback_color	"#1f222f"
#bspc config urgent_border_color 	"#dd2727"

bspc monitor -d 一 二 三 四 五 六 七 八 九 十
#bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc rule -a Chromium desktop ='^1'
bspc rule -a Spotify desktop='^3'
bspc rule -a discord desktop='^2'

bspc rule -a Xfce4-settings-manager state=tiled

